version: "3"
services:
  api:
    stdin_open: true
    # tty: true
    restart: always
    working_dir: /app
    build: .
    command: bundle exec rackup -d -p 9292 -o 0.0.0.0
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
    ports:
      - 9292:9292
volumes:
  db:
  esdata:
    driver: local