
source 'https://rubygems.org'

gem 'json'
gem 'curb'
gem 'tty-spinner'
gem 'rspec'
gem 'coderay'
gem 'rack-test'
gem 'sinatra'
gem 'byebug'
gem 'puma'
gem 'sinatra-contrib'
gem 'rest-client'
gem 'sinatra-cross_origin'
gem 'nokogiri'